import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type VoucherDocument = Voucher & Document;

export enum VoucherType {
    PERCENTAGE = 'percentage',     // Giảm theo %
    FIXED_AMOUNT = 'fixed_amount', // Giảm cố định
    FREE_SERVICE = 'free_service', // Tặng dịch vụ
    FREE_SHIPPING = 'free_shipping', // Miễn phí vận chuyển (nếu có)
}

export enum VoucherApplicable {
    ALL = 'all',
    SPECIFIC_SERVICES = 'specific_services',
    SPECIFIC_CATEGORIES = 'specific_categories',
    FIRST_BOOKING = 'first_booking',
    BIRTHDAY = 'birthday',
    MEMBER_ONLY = 'member_only',
}

export enum VoucherStatus {
    ACTIVE = 'active',
    INACTIVE = 'inactive',
    EXPIRED = 'expired',
    DEPLETED = 'depleted', // Đã hết lượt
}

@Schema({ timestamps: true })
export class Voucher {
    @Prop({ required: true, unique: true, uppercase: true, index: true })
    code: string; // VD:  SUMMER2025, WELCOME50

    @Prop({ required: true })
    name: string;

    @Prop()
    description?: string;

    // ===== Loại giảm giá =====
    @Prop({ enum: VoucherType, required: true })
    type: VoucherType;

    // ===== Giá trị giảm =====
    @Prop({ required: true, min: 0 })
    discountValue: number; // % hoặc số tiền

    @Prop({ min: 0 })
    maxDiscountAmount?: number; // Giảm tối đa (cho type PERCENTAGE)

    // ===== Điều kiện áp dụng =====
    @Prop({ default: 0, min: 0 })
    minOrderAmount: number; // Đơn hàng tối thiểu

    @Prop({ enum: VoucherApplicable, default: VoucherApplicable.ALL })
    applicableTo: VoucherApplicable;

    @Prop({ type: [{ type: Types.ObjectId, ref: 'Service' }], default: [] })
    applicableServices: Types.ObjectId[];

    @Prop({ type: [{ type: Types.ObjectId, ref: 'ServiceCategory' }], default: [] })
    applicableCategories: Types.ObjectId[];

    // ===== Thời gian =====
    @Prop({ required: true })
    validFrom: Date;

    @Prop({ required: true })
    validUntil: Date;

    // ===== Giới hạn sử dụng =====
    @Prop()
    totalUsageLimit?: number; // Tổng số lần sử dụng

    @Prop({ default: 0 })
    currentUsageCount: number;

    @Prop({ default: 1 })
    usagePerUser: number; // Mỗi user dùng được mấy lần

    // ===== Áp dụng cho ai =====
    @Prop({ type: [{ type: Types.ObjectId, ref: 'User' }], default: [] })
    specificUsers: Types.ObjectId[]; // Voucher cá nhân

    @Prop({ type: [String], default: [] })
    applicableMembershipTiers: string[]; // ['gold', 'platinum']

    @Prop({ type: [String], default: [] })
    excludedMembershipTiers: string[]; // Loại trừ tier nào

    // ===== Trạng thái =====
    @Prop({ enum: VoucherStatus, default: VoucherStatus.ACTIVE, index: true })
    status: VoucherStatus;

    @Prop({ default: false })
    isPublic: boolean; // Hiển thị công khai hay không

    @Prop({ default: false })
    isAutoApply: boolean; // Tự động áp dụng nếu đủ điều kiện

    // ===== Hình ảnh & Display =====
    @Prop()
    image?: string;

    @Prop()
    bannerImage?: string;

    @Prop({ default: 0 })
    displayOrder: number;

    // ===== Tracking =====
    @Prop({ type: [{ type: Types.ObjectId, ref: 'User' }], default: [] })
    usedBy: Types.ObjectId[];

    @Prop({ type: Map, of: Number, default: {} })
    usageCountByUser: Map<string, number>; // userId -> count

    @Prop({ default: 0 })
    totalSavingsAmount: number; // Tổng tiền đã giảm

    // ===== Stacking & Combination =====
    @Prop({ default: false })
    canStackWithOthers: boolean; // Có thể dùng cùng voucher khác

    @Prop({ default: false })
    canCombineWithPoints: boolean; // Có thể dùng cùng điểm

    // ===== Auto-generation settings =====
    @Prop({ default: false })
    isAutoGenerated: boolean;

    @Prop()
    generatedFor?: string; // 'birthday', 'referral', 'loyalty'

    // ===== Admin info =====
    @Prop({ type: Types.ObjectId, ref: 'User' })
    createdBy?: Types.ObjectId;

    @Prop()
    notes?: string; // Ghi chú nội bộ
}

export const VoucherSchema = SchemaFactory.createForClass(Voucher);

// ===== Indexes =====
VoucherSchema.index({ code: 1 });
VoucherSchema.index({ status: 1, validFrom: 1, validUntil: 1 });
VoucherSchema.index({ applicableTo: 1 });
VoucherSchema.index({ isPublic: 1, status: 1 });

// ===== Pre-save:  Auto-update status =====
VoucherSchema.pre('save', function () {
    const now = new Date();

    // Check expired
    if (now > this.validUntil) {
        this.status = VoucherStatus.EXPIRED;
    }

    // Check depleted
    if (this.totalUsageLimit && this.currentUsageCount >= this.totalUsageLimit) {
        this.status = VoucherStatus.DEPLETED;
    }

    // Uppercase code
    if (this.code) {
        this.code = this.code.toUpperCase().trim();
    }
});

// ===== Methods =====
VoucherSchema.methods.canBeUsedBy = function (userId: string, orderAmount: number, membershipTier?: string): {
    valid: boolean;
    reason?: string;
} {
    // Check status
    if (this.status !== VoucherStatus.ACTIVE) {
        return { valid: false, reason: `Voucher ${this.status}` };
    }

    // Check date range
    const now = new Date();
    if (now < this.validFrom) {
        return { valid: false, reason: 'Voucher chưa có hiệu lực' };
    }
    if (now > this.validUntil) {
        return { valid: false, reason: 'Voucher đã hết hạn' };
    }

    // Check min order amount
    if (orderAmount < this.minOrderAmount) {
        return { valid: false, reason: `Đơn hàng tối thiểu ${this.minOrderAmount.toLocaleString()}đ` };
    }

    // Check usage limit
    if (this.totalUsageLimit && this.currentUsageCount >= this.totalUsageLimit) {
        return { valid: false, reason: 'Voucher đã hết lượt sử dụng' };
    }

    // Check per-user limit
    const userUsageCount = this.usageCountByUser.get(userId) || 0;
    if (userUsageCount >= this.usagePerUser) {
        return { valid: false, reason: 'Bạn đã sử dụng hết lượt cho voucher này' };
    }

    // Check specific users
    if (this.specificUsers.length > 0 && !this.specificUsers.includes(userId as any)) {
        return { valid: false, reason: 'Voucher không dành cho bạn' };
    }

    // Check membership tier
    if (this.applicableMembershipTiers.length > 0) {
        if (!membershipTier || !this.applicableMembershipTiers.includes(membershipTier)) {
            return { valid: false, reason: `Voucher chỉ dành cho hội viên ${this.applicableMembershipTiers.join(', ')}` };
        }
    }

    if (this.excludedMembershipTiers.length > 0) {
        if (membershipTier && this.excludedMembershipTiers.includes(membershipTier)) {
            return { valid: false, reason: 'Voucher không áp dụng cho hạng thành viên của bạn' };
        }
    }

    return { valid: true };
};

VoucherSchema.methods.calculateDiscount = function (orderAmount: number): number {
    let discount = 0;

    switch (this.type) {
        case VoucherType.PERCENTAGE:
            discount = (orderAmount * this.discountValue) / 100;
            if (this.maxDiscountAmount) {
                discount = Math.min(discount, this.maxDiscountAmount);
            }
            break;

        case VoucherType.FIXED_AMOUNT:
            discount = this.discountValue;
            break;

        case VoucherType.FREE_SERVICE:
            // Handle in booking logic
            discount = 0;
            break;

        default:
            discount = 0;
    }

    return Math.min(discount, orderAmount);
};

VoucherSchema.methods.use = async function (userId: string, discountAmount: number) {
    this.currentUsageCount += 1;

    if (!this.usedBy.includes(userId as any)) {
        this.usedBy.push(userId as any);
    }

    const currentCount = this.usageCountByUser.get(userId) || 0;
    this.usageCountByUser.set(userId, currentCount + 1);

    this.totalSavingsAmount += discountAmount;

    return this.save();
};